[build]
target = "riscv32imafc-unknown-none-elf"
rustflags = ['-Clink-arg=-Tlds/virt.lds']

[target.riscv32imafc-unknown-none-elf]
runner = "./run.sh"

[term]
quiet = false
verbose = true
color = 'auto'
